
Alternative Memory Debugging
============================
:nofooter:  // Prevent obnoxious "last modified" thing by not having footer

FIXME: -fno-omit-frame-pointer -fsanitize=address -fsanitize=leak probably
deserve a mention here

The link:http://valgrind.org[valgrind] program does a really good job finding
memory bugs.  But if for some reason you don't want to use it there are some
alternatives:

* Create wrappers for `malloc()`, `calloc()`, `free()` etc. that print what
they're doing when they run.  This stategy is probably most useful when you're
starting with strong suspiciouns about which calls are involved in a problem --
just substitute wrapper calls for the suspects.

* Define macros called `malloc()`, `calloc()` etc. that call wrapper functions
defined as described above.  This strategy can be used to easily substitute
your wrappers for all calls wherever these macros are defined.  This approach
will fail if your program takes the addresses of the underlying allocation
functions.

* Use the GNU `ld` `--wrap` option.  This approach will work even if your
program takes the address of the underlying allocation functions.  The
disadvantage is that it's link-wide, so cannot be applied selectively to
particularly suspicious call sites.  Calls from libraries (e.g. libc's
`strdup()`) will not be intercepted.  Bonus hint: when following the example
in the `ld` documentation, it's useful to also declare `__real_malloc()` like
so:
+
[source, c]
----
void *__real_malloc (size_t size);
----
+
This will prevent compile-time warnings about implicit declarations.

* I _do not_ recommend using malloc interposition libraries, for the reasons
described
link:https://blogs.oracle.com/quenelle/entry/malloc_interposition_can_t_possibly[here].
Wrappers are fine, things that don't ultimately allocate or free memory by
calling exactly the routines they're replacing at each call site not so much.
Some interposition libraries meet this criteria, but many don't.

Note that memory problems frequently involve allocatin in other functions (e.g.
libc's `strdup()`), which then also need to be instrumented using one of the
methods described above.  The set of functions that you end up needing to
instrument can be annoyingly large.
