
// Note: this file is intended to be used with asciidoctor rather than asciidoc

Ditch Your Debugger
===================
:nofooter:  // Prevent obnoxious "last modified" thing by not having footer

Here's <<why_debuggers_are_bad.adoc#, why debuggers are bad>>.

This article describes an alternative approach.  There's a tiny
<<source_library.adoc#, source library>> (just a single .c/.h pair) that
implements some of these ideas, and an optional demo setup for it.

_Study_ first, _then_ type.  The items below are best used to test beliefs, not
create them.

Things You Need to Avoid the Debugger
-------------------------------------

* Convenient checkpoints and value output.  See the the `CP()`, `TV()` and
`TS()` macros from the <<source_library.adoc#, source library>>, or make editor
macros for things like this:
+
[source, c]
----
printf ("%s:%i:%s: checkpoint\n", __FILE__, __LINE__, __func__);
----
if you don't like having to tell `printf()` what type you're printing when the
compiler already knows, check out the the `PT()` and `TP()` macros from the
optional `instrument_format_free_print.h` header in the
<<source_library.adoc#, source library>> download.

* A way to get a backtrace.  The (GNU-specific) `backtrace()` function and the
`addr2line` program can do this.  See the `backtrace_with_line_numbers()`
function or `BT_ASSERT()` macro from the
<<source_library.adoc#, source library>>.
  
* A way to look up the function and source location pointed to by a function
pointer, so you can use instrumentation to find out what's going to be called
from a given point at run time.  See `what_func()` from the
<<source_library.adoc#, source library>> which does this using the `nm` program
and dladdr() function.

* A strategy for dealing with memory errors.  I use
link:http://valgrind.org[valgrind] like this:
+
[source, sh]
----
valgrind --leak-check=yes --undef-value-errors=no ./my_exe my_exe_arg 2>&1 | tee /tmp/valgrind_log
----
Valgrind looks sort of like a debugger, but you don't have to
operate _inside_ it.  There are 
<<alternative_memory_debugging.adoc#, other options>>, however.

* A strategy for exploring your program's call tree and sources statically.  I
use link:http://www.vim.org[vim] and link:http://cscope.sourceforge.net[cscope]
for C, and link:https://www.gnu.org/software/global/[GNU global] or
link:http://ctags.sourceforge.net[exuberant ctags] for other
things.  For whole-system exploration I like the HTML call graph and linked
sources that link:https://www.gnu.org/software/global/[global] produces.
The <<source_library.adoc#, source library>> includes an example of how to
integrate link:http://www.gnu.org/software/cflow/[GNU cflow] and
link:https://www.gnu.org/software/global/[global] into your build system (in
`Makefile` and `cflow_and_global.mk` files).

* A decent build system, i.e. one that can rebuild your program fast.  There
are several things that may help with this:

** The link:https://ccache.samba.org[ccache] program caches the results of
compilation commands and reuses them when appropriate.  It's particularly
helpful when your build system often rebuilds too much.  It's simple to use:
just replacing `gcc` with `ccache gcc` in your compilation recipes is usually
enough.  See the `Makefile` in the <<source_library.adoc#, source library>> for
an example.

** GNU link:https://www.gnu.org/software/binutils/[binutils] includes a new
linker called `gold`.  It can do incremental linking, which is much faster for
large projects.  See the `Makefile` in the <<source_library.adoc#, source
library>> for details.

** The GNU link:https://www.gnu.org/software/automake/[automake] and
link:http://www.gnu.org/software/autoconf/autoconf.html[autoconf] systems can
add dependency tracking to your program automatically.  They aren't simple to
use generally, but if you know you're headed in that direction anyway it might
be worth adopting them sooner rather than later.

This stuff can be extended arbitrarily.  If you need to write some code to
visualize your data you can do so in the most natural way using the language at
hand, without any discontinuity between your basic instrumentation and those
extensions.
